**Fuente**
OECD - Organisation for economic co-operation and development

**Información**
Female share of seats on boards of the largest publicly listed companies

**Enlace**
https://stats.oecd.org/index.aspx?queryid=54753

In [1]:
import pandas as pd
import numpy as np

In [2]:
women_boards_worldwide = pd.read_csv('Female share of seats on boards of the largest publicly listed companies.csv')

In [3]:
women_boards_worldwide = women_boards_worldwide[['Country', 'Time', 'Value']]
women_boards_worldwide.sort_values(by=['Country'], inplace=True)
women_boards_worldwide.reset_index(drop=True, inplace=True)
women_boards_worldwide

           Country  Time  Value
0        Australia  2016   26.0
1        Australia  2019   31.2
2        Australia  2018   31.5
3        Australia  2021   34.8
4        Australia  2020   34.0
..             ...   ...    ...
415  United States  2016   20.3
416  United States  2018   23.4
417  United States  2020   28.2
418  United States  2019   26.1
419  United States  2021   29.7

[420 rows x 3 columns]

In [6]:
country_list = women_boards_worldwide.Country.unique()
country_list = country_list.tolist()
print(country_list)
year_column_list = women_boards_worldwide.Time.unique()
year_column_list = sorted(year_column_list)
print(year_column_list)

['Australia', 'Austria', 'Belgium', 'Brazil', 'Canada', 'Chile', "China (People's Republic of)", 'Colombia', 'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Ireland', 'Israel', 'Italy', 'Japan', 'Korea', 'Latvia', 'Lithuania', 'Luxembourg', 'Mexico', 'Netherlands', 'New Zealand', 'Norway', 'OECD - Average', 'Poland', 'Portugal', 'Russia', 'Slovak Republic', 'Slovenia', 'South Africa', 'Spain', 'Sweden', 'Switzerland', 'Türkiye', 'United Kingdom', 'United States']
[2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]

In [7]:
def get_year_values(year, country_list):
    year_list = []
    for country in country_list:
        try:
            value = women_boards_worldwide[(women_boards_worldwide['Country'] == str(country)) & (women_boards_worldwide['Time'] == year)][['Value']]
            value_ = (value.values[0])[0]
            year_list.append(value_)
        except:
            year_list.append('NaaN')
    return year_list

In [8]:
def get_columns_dictionary(year_column_list,country_list):
    column_dictionary = {}
    column_dictionary['Country'] = country_list
    for year in year_column_list:
        if str(year) not in column_dictionary.keys():
            column_dictionary[str(year)] = get_year_values(year, country_list)
        else:
            column_dictionary[str(year)].append(get_year_values(year, country_list))

    return column_dictionary

In [9]:
years_dictionary = get_columns_dictionary(year_column_list,country_list)

In [10]:
women_boards_worldwide_dataframe = pd.DataFrame.from_dict(years_dictionary)

In [23]:
max_value = women_boards_worldwide_dataframe['2021'].max()
women_boards_worldwide_dataframe[women_boards_worldwide_dataframe['2021']==max_value]['Country']

16    Iceland
Name: Country, dtype: object

In [24]:
max_value = women_boards_worldwide_dataframe['2021'].min()
women_boards_worldwide_dataframe[women_boards_worldwide_dataframe['2021']==max_value]['Country']

23    Korea
Name: Country, dtype: object

In [11]:
women_boards_worldwide_dataframe.sort_values(by=['2021'])
16]

,Country,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
23,Korea,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,2.4,2.1,2.3,3.3,4.9,8.7
10,Estonia,7.0,6.7,7.8,7.3,7.1,8.1,8.8,7.4,8.0,9.4,8.8,9.1
15,Hungary,13.6,5.3,7.4,11.3,11.8,17.8,12.3,14.5,14.9,12.9,9.9,9.4
27,Mexico,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,7.2,7.5,7.3,8.1,9.0,10.6
34,Russia,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,6.8,7.0,9.2,10.6,10.5,12.0
18,Indonesia,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,2.8,3.3,3.3,10.1,5.7,12.2
22,Japan,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,4.8,5.3,6.4,8.4,10.7,12.6
7,Colombia,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,13.4,15.1,13.2,13.5,12.5,12.9
6,China (People's Republic of),NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,8.5,9.7,11.1,11.4,13.0,13.8
5,Chile,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,7.7,8.2,8.4,8.5,9.9,15.2
3,Brazil,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,5.8,8.4,8.0,11.9,13.7,16.9
17,India,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,12.8,13.8,14.0,15.9,16.6,17.1
41,Türkiye,9.7,11.0,9.6,8.5,8.7,10.4,12.6,13.4,15.3,18.1,17.5,18.0
36,Slovenia,9.8,14.2,18.7,21.6,19.9,21.5,24.8,22.6,27.9,24.6,22.9,19.4
14,Greece,6.2,6.5,7.9,8.4,8.9,9.8,9.1,11.3,9.1,10.3,13.0,19.6
24,Latvia,23.5,26.6,28.2,28.6,31.7,30.4,28.5,28.8,29.0,31.7,25.6,22.2
25,Lithuania,13.1,14.0,17.8,16.1,16.5,14.3,14.3,14.3,10.8,12.0,14.3,22.3
26,Luxembourg,3.5,5.6,9.7,11.3,11.7,12.1,12.9,12.0,13.3,13.1,18.2,22.4
8,Czech Republic,12.2,15.9,16.4,11.3,3.5,10.4,10.1,14.5,13.8,18.2,17.2,23.0
32,Poland,11.6,11.8,11.8,12.3,14.6,19.4,18.8,20.1,21.0,23.5,22.8,24.7
20,Israel,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,21.8,23.1,24.5,21.6,24.3,26.7
35,Slovak Republic,21.6,14.6,13.8,24.0,18.2,12.7,12.5,15.1,24.1,29.1,31.4,27.7
31,OECD - Average,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,21.0,22.1,23.4,25.2,26.3,28.0
43,United States,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,20.3,21.7,23.4,26.1,28.2,29.7
40,Switzerland,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,17.5,21.3,22.3,24.9,26.7,30.0
19,Ireland,8.4,8.8,8.7,11.1,10.9,15.3,16.5,17.6,18.7,26.0,28.8,30.2
33,Portugal,5.4,5.9,7.4,8.8,9.5,13.5,14.3,16.2,21.6,24.6,26.6,31.0
38,Spain,9.5,11.1,12.3,14.8,16.9,18.7,20.3,22.0,23.7,26.4,29.3,32.6
4,Canada,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,22.8,25.8,27.0,29.1,31.3,32.9
37,South Africa,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,18.7,21.4,24.6,27.4,28.8,34.0
1,Austria,8.7,11.1,11.9,12.6,17.1,20.0,18.1,19.2,26.1,31.3,31.5,34.6
0,Australia,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,26.0,28.7,31.5,31.2,34.0,34.8
9,Denmark,17.7,16.3,20.8,22.9,24.0,25.8,27.1,30.3,27.7,30.0,33.6,34.9
11,Finland,25.9,26.5,28.6,29.8,29.2,29.2,30.1,32.8,34.5,34.2,35.1,35.2
13,Germany,12.6,15.2,17.9,21.5,24.4,26.1,29.5,31.9,33.8,35.6,36.3,36.0
42,United Kingdom,13.3,16.3,18.8,21.0,24.2,27.8,27.0,27.2,29.9,32.6,34.7,37.8
39,Sweden,26.4,24.7,25.5,26.5,27.6,32.6,36.9,36.3,36.1,37.5,38.0,37.9
2,Belgium,10.5,10.9,12.9,16.7,22.4,26.0,28.6,30.7,32.0,35.9,38.4,37.9
28,Netherlands,14.9,17.8,21.5,25.1,24.9,25.5,27.5,29.5,30.7,34.2,36.6,38.1
21,Italy,4.5,5.9,10.8,15.0,24.1,28.6,32.3,34.0,36.4,36.1,38.4,38.8
30,Norway,38.9,41.3,43.7,42.0,37.6,38.8,42.6,42.1,40.2,40.2,40.4,41.5
29,New Zealand,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,29.6,30.0,30.2,38.2,43.0,43.5
12,France,12.3,21.6,25.1,29.7,32.4,35.6,41.2,43.4,43.9,45.3,45.1,45.3
16,Iceland,15.8,20.5,36.2,48.1,44.8,44.2,45.1,43.5,45.7,45.9,44.4,47.1

In [13]:
dataset_for_map_women_boards_worldwide = women_boards_worldwide_dataframe[['Country', '2021']]
dataset_for_map_women_boards_worldwide.to_csv('dataset_for_map_boards_worldwide.csv')

In [50]:
paises_seleccionados = [23, 10, 34, 22, 6, 3, 17, 32, 19, 38, 4, 43, 37, 0, 13, 42, 39, 12, 16]
paises_seleccionados_2021 = women_boards_worldwide_dataframe.iloc[women_boards_worldwide_dataframe.index.isin(paises_seleccionados)]
paises_seleccionados_2021 = paises_seleccionados_2021[['Country', '2021']]
paises_seleccionados_2021.rename(columns = {'2021':'females'}, inplace = True)
paises_seleccionados_2021["males"] = np.nan
paises_seleccionados_2021.reset_index(drop=True, inplace=True)
paises_seleccionados_2021

for i, row in paises_seleccionados_2021.iterrows(): 
    paises_seleccionados_2021['males'][i] = 100 - paises_seleccionados_2021['females'][i]

paises_seleccionados_2021
paises_seleccionados_2021.to_csv('paises_seleccionados_board_world_percentage.csv')

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [82]:
paises_seleccionados_2021

,Country,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
10,Estonia,7.0,6.7,7.8,7.3,7.1,8.1,8.8,7.4,8.0,9.4,8.8,9.1
12,France,12.3,21.6,25.1,29.7,32.4,35.6,41.2,43.4,43.9,45.3,45.1,45.3
15,Hungary,13.6,5.3,7.4,11.3,11.8,17.8,12.3,14.5,14.9,12.9,9.9,9.4
16,Iceland,15.8,20.5,36.2,48.1,44.8,44.2,45.1,43.5,45.7,45.9,44.4,47.1
23,Korea,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,2.4,2.1,2.3,3.3,4.9,8.7
29,New Zealand,NaaN,NaaN,NaaN,NaaN,NaaN,NaaN,29.6,30.0,30.2,38.2,43.0,43.5

In [78]:
paises_seleccionados_max_min = [23, 10, 15, 29, 12, 16]
paises_seleccionados_max_min = women_boards_worldwide_dataframe.iloc[women_boards_worldwide_dataframe.index.isin(paises_seleccionados_max_min)]
paises_seleccionados_max_min.to_csv('women_board_percentage_max_min_world.csv')

In [76]:
result = paises_seleccionados_max_min.dtypes
paises_seleccionados_max_min = paises_seleccionados_max_min.replace(['NaaN'],'0')
paises_seleccionados_max_min
paises_seleccionados_max_min['2010'] = paises_seleccionados_max_min['2010'].astype(float, errors = 'raise')
paises_seleccionados_max_min['2011'] = paises_seleccionados_max_min['2010'].astype(float, errors = 'raise')
paises_seleccionados_max_min['2012'] = paises_seleccionados_max_min['2010'].astype(float, errors = 'raise')
paises_seleccionados_max_min['2013'] = paises_seleccionados_max_min['2010'].astype(float, errors = 'raise')
paises_seleccionados_max_min['2014'] = paises_seleccionados_max_min['2010'].astype(float, errors = 'raise')
paises_seleccionados_max_min['2015'] = paises_seleccionados_max_min['2010'].astype(float, errors = 'raise')
result = paises_seleccionados_max_min.dtypes

Country     object
2010       float64
2011       float64
2012       float64
2013       float64
2014       float64
2015       float64
2016       float64
2017       float64
2018       float64
2019       float64
2020       float64
2021       float64
dtype: object

In [77]:
paises_seleccionados_max_min.to_csv('women_board_percentage_max_min_world.csv')

In [15]:
women_boards_worldwide.to_csv('all_women_boards_worldwide_percentage.csv')

In [83]:
women_boards_worldwide_max_min = women_boards_worldwide.loc[(women_boards_worldwide['Country'] == 'Estonia') | (women_boards_worldwide['Country'] == 'France') | (women_boards_worldwide['Country'] == 'Hungary') | (women_boards_worldwide['Country'] == 'Iceland') | (women_boards_worldwide['Country'] == 'Korea') | (women_boards_worldwide['Country'] == 'New Zealand')]

In [85]:
women_boards_worldwide_max_min
women_boards_worldwide_max_min.to_csv('women_board_percentage_max_min_world.csv')

In [86]:
women_boards_worldwide_max_min

         Country  Time  Value
84       Estonia  2012    7.8
85       Estonia  2010    7.0
86       Estonia  2020    8.8
87       Estonia  2017    7.4
88       Estonia  2021    9.1
89       Estonia  2014    7.1
90       Estonia  2013    7.3
91       Estonia  2016    8.8
92       Estonia  2015    8.1
93       Estonia  2018    8.0
94       Estonia  2019    9.4
95       Estonia  2011    6.7
108       France  2010   12.3
109       France  2016   41.2
110       France  2012   25.1
111       France  2014   32.4
112       France  2017   43.4
113       France  2019   45.3
114       France  2013   29.7
115       France  2015   35.6
116       France  2020   45.1
117       France  2011   21.6
118       France  2021   45.3
119       France  2018   43.9
144      Hungary  2016   12.3
145      Hungary  2010   13.6
146      Hungary  2021    9.4
147      Hungary  2014   11.8
148      Hungary  2011    5.3
149      Hungary  2013   11.3
150      Hungary  2017   14.5
151      Hungary  2020    9.9
152      Hungary  2015   17.8
153      Hungary  2012    7.4
154      Hungary  2018   14.9
155      Hungary  2019   12.9
156      Iceland  2012   36.2
157      Iceland  2021   47.1
158      Iceland  2011   20.5
159      Iceland  2014   44.8
160      Iceland  2020   44.4
161      Iceland  2017   43.5
162      Iceland  2016   45.1
163      Iceland  2010   15.8
164      Iceland  2018   45.7
165      Iceland  2019   45.9
166      Iceland  2015   44.2
167      Iceland  2013   48.1
216        Korea  2017    2.1
217        Korea  2019    3.3
218        Korea  2016    2.4
219        Korea  2020    4.9
220        Korea  2018    2.3
221        Korea  2021    8.7
276  New Zealand  2016   29.6
277  New Zealand  2018   30.2
278  New Zealand  2021   43.5
279  New Zealand  2019   38.2
280  New Zealand  2017   30.0
281  New Zealand  2020   43.0