**Fuente**
OECD - Organisation for economic co-operation and development

**Información**
Share of female managers

**Enlace**
https://stats.oecd.org/index.aspx?queryid=54753#

In [37]:
import pandas as pd
import numpy as np

In [51]:
women_managers_worldwide = pd.read_csv('Share of female managers.csv')

In [52]:
pd.set_option('max_columns', None)
women_managers_worldwide = women_managers_worldwide[['Country', 'Time', 'Value']]
pd.set_option('max_columns', None)
women_managers_worldwide

            Country  Time  Value
0         Australia  2011   36.1
1         Australia  2012   35.7
2         Australia  2013   35.8
3         Australia  2014   36.3
4         Australia  2015   37.7
..              ...   ...    ...
472          Latvia  2021   45.9
473       Lithuania  2021   37.0
474        Slovenia  2021   34.0
475    South Africa  2021   31.6
476  OECD - Average  2021   33.7

[477 rows x 3 columns]

In [66]:
women_managers_worldwide.to_csv('all_women_managers_percentage_worldwide.csv')

In [5]:
women_managers_worldwide.sort_values(by=['Country'], inplace=True)
country_list = women_managers_worldwide.Country.unique()
country_list = country_list.tolist()
print(country_list)
year_column_list = women_managers_worldwide.Time.unique()
year_column_list = sorted(year_column_list)
print(year_column_list)

['Australia', 'Austria', 'Belgium', 'Brazil', 'Canada', 'Chile', 'Costa Rica', 'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Ireland', 'Israel', 'Italy', 'Japan', 'Korea', 'Latvia', 'Lithuania', 'Luxembourg', 'Mexico', 'Netherlands', 'Norway', 'OECD - Average', 'Poland', 'Portugal', 'Russia', 'Slovak Republic', 'Slovenia', 'South Africa', 'Spain', 'Sweden', 'Switzerland', 'Türkiye', 'United Kingdom', 'United States']
[2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]

In [6]:
def get_year_values(year, country_list):
    year_list = []
    for country in country_list:
        try:
            value = women_managers_worldwide[(women_managers_worldwide['Country'] == str(country)) & (women_managers_worldwide['Time'] == year)][['Value']]
            value_ = (value.values[0])[0]
            year_list.append(value_)
        except:
            year_list.append('NaaN')
    return year_list

In [7]:
def get_columns_dictionary(year_column_list,country_list):
    column_dictionary = {}
    column_dictionary['Country'] = country_list
    for year in year_column_list:
        if str(year) not in column_dictionary.keys():
            column_dictionary[str(year)] = get_year_values(year, country_list)
        else:
            column_dictionary[str(year)].append(get_year_values(year, country_list))

    return column_dictionary

In [8]:
years_dictionary_managers = get_columns_dictionary(year_column_list,country_list)

In [21]:
women_managers_worldwide_dataframe = pd.DataFrame.from_dict(years_dictionary_managers)
women_managers_worldwide_dataframe

,Country,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Australia,34.4,36.1,35.7,35.8,36.3,37.7,36.7,38.7,37.8,39.2,40.0,NaaN
1,Austria,28.9,27.5,30.1,29.3,30.3,29.7,31.8,31.8,31.6,33.2,32.8,35.5
2,Belgium,34.1,29.9,32.4,31.4,31.7,32.6,32.7,33.5,33.9,32.7,34.5,35.4
3,Brazil,NaaN,36.1,37.2,37.3,37.8,38.5,39.0,39.1,38.7,38.4,36.8,38.7
4,Canada,36.8,37.1,36.4,35.8,35.5,36.3,NaaN,34.5,35.1,35.3,35.8,35.6
5,Chile,23.8,23.6,24.0,25.0,26.9,27.4,27.4,26.5,27.3,29.9,27.4,30.4
6,Costa Rica,30.0,35.2,28.7,36.8,31.9,28.7,34.6,41.0,37.1,40.5,59.4,40.2
7,Czech Republic,27.7,25.8,26.2,27.2,27.9,29.5,25.4,24.6,26.8,26.8,27.8,28.4
8,Denmark,21.9,27.8,28.4,26.7,26.0,26.3,27.5,26.3,26.1,26.8,27.9,28.2
9,Estonia,36.1,35.4,31.8,33.4,32.6,31.1,36.5,38.9,36.5,37.8,37.5,41.2
10,Finland,30.4,32.0,29.7,29.6,33.7,33.3,34.1,31.3,31.8,36.9,37.5,36.5
11,France,38.5,39.3,39.3,36.0,32.7,31.8,33.1,33.4,34.4,34.7,35.5,37.8
12,Germany,29.9,30.3,28.6,28.9,29.0,29.3,29.3,29.2,29.4,29.4,28.9,29.2
13,Greece,30.2,23.6,26.0,28.8,28.3,25.7,25.5,29.8,27.5,28.0,29.4,29.6
14,Hungary,36.5,40.4,38.9,40.8,39.8,40.5,39.4,39.4,38.6,38.9,39.2,37.3
15,Iceland,34.3,39.8,39.9,37.6,37.2,38.2,34.2,32.4,41.5,41.9,38.6,37.6
16,India,12.2,NaaN,12.9,NaaN,NaaN,NaaN,NaaN,NaaN,13.7,14.6,17.6,NaaN
17,Indonesia,20.9,NaaN,19.3,21.6,23.5,22.4,44.8,27.5,NaaN,29.6,32.6,32.4
18,Ireland,39.1,33.8,33.2,33.3,33.7,34.6,36.2,36.2,36.0,35.3,36.3,38.0
19,Israel,34.7,35.5,32.2,32.8,32.9,32.3,34.2,34.6,NaaN,NaaN,NaaN,NaaN
20,Italy,32.8,25.1,26.0,27.0,26.6,26.6,27.7,27.5,27.0,27.8,27.3,28.6
21,Japan,10.4,11.7,11.3,10.9,11.4,NaaN,13.3,12.8,NaaN,NaaN,13.3,13.2
22,Korea,9.4,10.1,11.1,11.4,11.1,10.5,9.8,12.3,14.5,15.4,15.6,16.3
23,Latvia,42.1,45.5,45.8,43.8,44.1,44.3,47.2,46.3,44.9,45.8,46.9,45.9
24,Lithuania,41.1,39.1,38.9,39.6,38.6,39.6,39.4,39.3,39.2,39.2,37.9,37.0
25,Luxembourg,24.7,24.0,18.0,14.9,22.5,18.2,17.7,18.8,24.5,25.8,26.3,21.9
26,Mexico,NaaN,NaaN,NaaN,35.0,35.4,36.0,36.0,36.7,36.0,36.0,38.4,38.5
27,Netherlands,28.4,29.3,28.8,24.6,25.5,26.0,25.4,26.6,25.7,27.1,26.2,26.0
28,Norway,34.4,31.4,32.2,32.9,35.5,36.0,37.9,38.3,35.6,34.5,34.0,33.5
29,OECD - Average,31.3,31.2,31.0,30.9,31.2,31.3,32.1,32.3,33.0,34.0,34.2,33.7
30,Poland,35.6,38.0,37.8,37.8,38.8,40.2,41.2,41.2,42.5,43.1,43.3,43.0
31,Portugal,32.3,33.4,35.2,33.8,35.1,32.6,35.9,34.3,34.0,37.2,35.7,38.0
32,Russia,38.6,39.5,39.1,38.4,38.1,38.7,42.0,41.3,41.8,44.7,45.7,NaaN
33,Slovak Republic,34.6,30.9,33.1,32.7,30.0,31.3,35.0,32.8,32.1,33.7,35.5,37.3
34,Slovenia,34.8,38.4,39.0,37.0,37.5,37.4,40.8,41.2,38.5,40.1,40.1,34.0
35,South Africa,29.6,31.0,31.1,30.0,31.1,30.8,31.6,32.1,30.5,30.2,31.4,31.6
36,Spain,34.3,29.9,30.2,30.8,30.9,31.4,31.2,30.6,32.1,33.2,35.0,33.3
37,Sweden,31.4,34.5,35.5,35.4,37.1,39.5,39.3,38.9,38.1,40.3,42.3,43.0
38,Switzerland,33.5,30.7,30.5,29.8,30.8,32.3,32.8,30.4,31.7,33.5,33.3,31.9
39,Türkiye,10.0,11.0,12.1,14.4,13.4,13.2,15.1,15.0,14.8,16.2,18.2,NaaN
40,United Kingdom,35.7,34.6,34.4,33.9,35.3,35.4,36.0,36.1,36.3,36.8,NaaN,NaaN
41,United States,NaaN,38.9,39.3,38.9,38.9,39.6,39.7,40.5,40.7,40.7,41.1,41.4

In [58]:
women_managers_worldwide_dataframe = women_managers_worldwide_dataframe.replace(['NaaN'],np.NaN)
women_managers_worldwide_dataframe.loc[women_managers_worldwide_dataframe['2021'].isnull(),'2021'] = women_managers_worldwide_dataframe['2020']
women_managers_worldwide_dataframe.loc[women_managers_worldwide_dataframe['2021'].isnull(),'2021'] = women_managers_worldwide_dataframe['2019']
women_managers_worldwide_dataframe.loc[women_managers_worldwide_dataframe['2021'].isnull(),'2021'] = women_managers_worldwide_dataframe['2018']
women_managers_worldwide_dataframe.loc[women_managers_worldwide_dataframe['2021'].isnull(),'2021'] = women_managers_worldwide_dataframe['2017']

women_managers_worldwide_dataframe.sort_values(by=['2021'])

,Country,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
21,Japan,10.4,11.7,11.3,10.9,11.4,NaN,13.3,12.8,NaN,NaN,13.3,13.2
22,Korea,9.4,10.1,11.1,11.4,11.1,10.5,9.8,12.3,14.5,15.4,15.6,16.3
16,India,12.2,NaN,12.9,NaN,NaN,NaN,NaN,NaN,13.7,14.6,17.6,17.6
39,Türkiye,10.0,11.0,12.1,14.4,13.4,13.2,15.1,15.0,14.8,16.2,18.2,18.2
25,Luxembourg,24.7,24.0,18.0,14.9,22.5,18.2,17.7,18.8,24.5,25.8,26.3,21.9
27,Netherlands,28.4,29.3,28.8,24.6,25.5,26.0,25.4,26.6,25.7,27.1,26.2,26.0
8,Denmark,21.9,27.8,28.4,26.7,26.0,26.3,27.5,26.3,26.1,26.8,27.9,28.2
7,Czech Republic,27.7,25.8,26.2,27.2,27.9,29.5,25.4,24.6,26.8,26.8,27.8,28.4
20,Italy,32.8,25.1,26.0,27.0,26.6,26.6,27.7,27.5,27.0,27.8,27.3,28.6
12,Germany,29.9,30.3,28.6,28.9,29.0,29.3,29.3,29.2,29.4,29.4,28.9,29.2
13,Greece,30.2,23.6,26.0,28.8,28.3,25.7,25.5,29.8,27.5,28.0,29.4,29.6
5,Chile,23.8,23.6,24.0,25.0,26.9,27.4,27.4,26.5,27.3,29.9,27.4,30.4
35,South Africa,29.6,31.0,31.1,30.0,31.1,30.8,31.6,32.1,30.5,30.2,31.4,31.6
38,Switzerland,33.5,30.7,30.5,29.8,30.8,32.3,32.8,30.4,31.7,33.5,33.3,31.9
17,Indonesia,20.9,NaN,19.3,21.6,23.5,22.4,44.8,27.5,NaN,29.6,32.6,32.4
36,Spain,34.3,29.9,30.2,30.8,30.9,31.4,31.2,30.6,32.1,33.2,35.0,33.3
28,Norway,34.4,31.4,32.2,32.9,35.5,36.0,37.9,38.3,35.6,34.5,34.0,33.5
29,OECD - Average,31.3,31.2,31.0,30.9,31.2,31.3,32.1,32.3,33.0,34.0,34.2,33.7
34,Slovenia,34.8,38.4,39.0,37.0,37.5,37.4,40.8,41.2,38.5,40.1,40.1,34.0
19,Israel,34.7,35.5,32.2,32.8,32.9,32.3,34.2,34.6,NaN,NaN,NaN,34.6
2,Belgium,34.1,29.9,32.4,31.4,31.7,32.6,32.7,33.5,33.9,32.7,34.5,35.4
1,Austria,28.9,27.5,30.1,29.3,30.3,29.7,31.8,31.8,31.6,33.2,32.8,35.5
4,Canada,36.8,37.1,36.4,35.8,35.5,36.3,NaN,34.5,35.1,35.3,35.8,35.6
10,Finland,30.4,32.0,29.7,29.6,33.7,33.3,34.1,31.3,31.8,36.9,37.5,36.5
40,United Kingdom,35.7,34.6,34.4,33.9,35.3,35.4,36.0,36.1,36.3,36.8,NaN,36.8
24,Lithuania,41.1,39.1,38.9,39.6,38.6,39.6,39.4,39.3,39.2,39.2,37.9,37.0
14,Hungary,36.5,40.4,38.9,40.8,39.8,40.5,39.4,39.4,38.6,38.9,39.2,37.3
33,Slovak Republic,34.6,30.9,33.1,32.7,30.0,31.3,35.0,32.8,32.1,33.7,35.5,37.3
15,Iceland,34.3,39.8,39.9,37.6,37.2,38.2,34.2,32.4,41.5,41.9,38.6,37.6
11,France,38.5,39.3,39.3,36.0,32.7,31.8,33.1,33.4,34.4,34.7,35.5,37.8
18,Ireland,39.1,33.8,33.2,33.3,33.7,34.6,36.2,36.2,36.0,35.3,36.3,38.0
31,Portugal,32.3,33.4,35.2,33.8,35.1,32.6,35.9,34.3,34.0,37.2,35.7,38.0
26,Mexico,NaN,NaN,NaN,35.0,35.4,36.0,36.0,36.7,36.0,36.0,38.4,38.5
3,Brazil,NaN,36.1,37.2,37.3,37.8,38.5,39.0,39.1,38.7,38.4,36.8,38.7
0,Australia,34.4,36.1,35.7,35.8,36.3,37.7,36.7,38.7,37.8,39.2,40.0,40.0
6,Costa Rica,30.0,35.2,28.7,36.8,31.9,28.7,34.6,41.0,37.1,40.5,59.4,40.2
9,Estonia,36.1,35.4,31.8,33.4,32.6,31.1,36.5,38.9,36.5,37.8,37.5,41.2
41,United States,NaN,38.9,39.3,38.9,38.9,39.6,39.7,40.5,40.7,40.7,41.1,41.4
30,Poland,35.6,38.0,37.8,37.8,38.8,40.2,41.2,41.2,42.5,43.1,43.3,43.0
37,Sweden,31.4,34.5,35.5,35.4,37.1,39.5,39.3,38.9,38.1,40.3,42.3,43.0
32,Russia,38.6,39.5,39.1,38.4,38.1,38.7,42.0,41.3,41.8,44.7,45.7,45.7
23,Latvia,42.1,45.5,45.8,43.8,44.1,44.3,47.2,46.3,44.9,45.8,46.9,45.9

In [65]:
paises_seleccionados = [15, 11, 37, 40, 12, 0, 35, 4, 36, 18, 41, 30, 16, 3, 21, 32, 9, 22]
paises_seleccionados_2021 = women_managers_worldwide_dataframe.iloc[women_managers_worldwide_dataframe.index.isin(paises_seleccionados)]

paises_seleccionados_2021 = women_managers_worldwide_dataframe.iloc[women_managers_worldwide_dataframe.index.isin(paises_seleccionados)]
paises_seleccionados_2021 = paises_seleccionados_2021[['Country', '2021']]
paises_seleccionados_2021.rename(columns = {'2021':'females'}, inplace = True)
paises_seleccionados_2021["males"] = np.nan
paises_seleccionados_2021.reset_index(drop=True, inplace=True)
paises_seleccionados_2021

for i, row in paises_seleccionados_2021.iterrows(): 
    paises_seleccionados_2021['males'][i] = 100 - paises_seleccionados_2021['females'][i]

paises_seleccionados_2021
paises_seleccionados_2021.to_csv('paises_seleccionados_managers_world_percentage.csv')
# paises_seleccionados_2021.rename(columns = {'2021':'females'}, inplace = True)
# paises_seleccionados_2021["males"] = np.nan
# paises_seleccionados_2021.reset_index(drop=True, inplace=True)
# paises_seleccionados_2021

# for i, row in paises_seleccionados_2021.iterrows(): 
#     paises_seleccionados_2021['males'][i] = 100 - paises_seleccionados_2021['females'][i]

# paises_seleccionados_2021
# paises_seleccionados_2021.to_csv('paises_seleccionados_board_world_percentage.csv')

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == "":

In [60]:
paises_seleccionados_2021.to_csv('paises_seleccionados_managers_world_percentage.csv')

In [64]:
women_managers_worldwide_max_min = women_managers_worldwide.loc[(women_managers_worldwide['Country'] == 'Japan') | (women_managers_worldwide['Country'] == 'Korea') | (women_managers_worldwide['Country'] == 'India') | (women_managers_worldwide['Country'] == 'Sweden') | (women_managers_worldwide['Country'] == 'Russia') | (women_managers_worldwide['Country'] == 'Latvia')]

women_managers_worldwide_max_min.to_csv('women_managers_percentage_max_min_world.csv')